### ISSUE TITLE
Fails to initialize the database on run.

### ISSUE THREAD

**Issue by Tron842** [PieInTheSky-Inc/YaDc#216]
After setting up the links for google cloud and discord and attempting to start the bot I am given an error failing to find the relation "settings".

```
Created service account connection file at: client_secrets.json
20210430 19:54:27 [INFO    ] discord.client: logging in using static token
20210430 19:54:27 [INFO    ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
20210430 19:54:27 [INFO    ] discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-main-2n97",{"micros":54396,"calls":["discord-sessions-prd-2-104",{"micros":53149,"calls":["start_session",{"micros":35854,"calls":["api-prd-main-xjxg",{"micros":30750,"calls":["get_user",{"micros":6345},"add_authorized_ip",{"micros":1912},"get_guilds",{"micros":3654},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":1865,"calls":[]}]}]}] (Session ID: <Redacted>).
+ on_connect()
Initializing.
Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\bot.py", line 134, in on_connect
    await __initialize()
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\bot.py", line 4056, in __initialize
    await db.init()
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\database.py", line 820, in init
    await __init_caches()
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\database.py", line 816, in __init_caches
    __settings_cache = await get_settings()
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\database.py", line 661, in get_settings
    records = await fetchall(query)
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\database.py", line 517, in fetchall
    raise pg_error
  File "E:\Users\<Redacted>\Downloads\Dolores Model T\src\database.py", line 515, in fetchall
    result = await connection.fetch(query)
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncpg\connection.py", line 583, in fetch
    return await self._execute(
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncpg\connection.py", line 1625, in _execute
    result, _ = await self.__execute(
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncpg\connection.py", line 1650, in __execute
    return await self._do_execute(
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncpg\connection.py", line 1677, in _do_execute
    stmt = await self._get_statement(
  File "C:\Users\<Redacted>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncpg\connection.py", line 375, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg\protocol\protocol.pyx", line 166, in prepare
asyncpg.exceptions.UndefinedTableError: relation "settings" does not exist
+ on_ready()
sys.argv: ['.\\bot.py']
Current time: 2021-04-30 23:54:29 (UTC)
Current Working Directory: E:\Users\<Redacted>\Downloads\Dolores Model T\src
Bot logged in as Doloris Model T (id=<Redacted>) on 1 servers
Bot version is: 1.3.4.1
[get_setting] UndefinedTableError while performing the query: SELECT * FROM settings WHERE settingname = $1
['schema_version']
MSG: relation "settings" does not exist
DB schema version is:
Python version: 3.9.4
discord.py version: 1.6.0
```

**Comment by Zukunftsmusik** [comment]
Fixed with v1.3.10.6
